Cleanup left-overs from the conversion, improve editing experience in IDEs like Eclipse and IntelliJ
eclipse/sparkplug pull request #272
Opened 2022-08-08 16:41 UTC by ahus1

I've been looking at the AsciiDoc setup used in this project to see it could be used for another upcoming specification at the Eclipse foundation. 

This tackles some of the things I found after opening it in my local IDE: 

* The updated build creates only a single output file as this avoids warnings about missing references, and as the title page would depend on attributes present only in the main document.
* Images and diagrams weren't showing in my IDE when I opened the separate chapters. Therefore I added `.asciidoctorconfig` files that have hints for the IDE to render a preview of the single chapters. The path to the PlantUML files is now an attribute so it can be adjusted whether a single chapter is viewed of the whole document. 
* The figure titles present from a previous conversion are now titles to the respective figure. This ensures that they are on the same page when creating for example a PDF. A future revision can reference their titles in the text.
* Some attribute are meant to be document level attributes and should go directly after the title in the main document. That why I reordered them in the main document.

Please let me know if this is helpful or if it needs additional mending of things.

2022-08-08 22:41 UTC, wes-johnson commented
This is helpful - thanks. However, chapter 5 didn't render for me. I got this in the logs - it seems the default config isn't quite right.

`ASP: Processing file:/Users/wes/dev/gitflow/Sparkplug/specification/src/main/asciidoc/chapters/Sparkplug_6_Payloads.adoc
ASP: WARN: skipping reference to missing attribute: assetsdir
ASP: ERROR: Failed to generate image: No such file or directory - /Users/<snip>/Sparkplug/specification/src/main/asciidoc/{assetsdir}assets/plantuml/host-session-establishment.puml
`

2022-08-08 22:43 UTC, wes-johnson requested changes
Please fix the 'assetsdir' default value so all chapters can render properly.

2022-08-09 08:32 UTC, ahus1 commented
Hi @wes-johnson - I've update the file `Sparkplug_5_Operational_Behavior.adoc` so it now contains a default value. 

Still I wonder where you saw that error message - a `gradlew build` didn't show any error to me even before the change.

It would be great to know how to reproduce the error message and I'd then fix any remaining issues.

2022-08-09 15:06 UTC, wes-johnson commented
@ahus1 - I simply opened chapter 5 in Eclipse and the error showed up in the console pane of Eclipse after it failed to render.

2022-08-09 15:40 UTC, ahus1 commented
@wes-johnson - I have now tested it with the latest version of Eclipse plus the Asciidoctor plugin for Eclipse, and I don't see this error any more. I also see that the PlantUML diagrams render in the preview.

Please re-review when you have the time. Thanks!

2022-08-09 16:37 UTC, wes-johnson approved these changes

2022-08-09 16:38 UTC, merged